### ISSUE TITLE
Error Running `mlem build <model> docker -c server.type=fastapi -c image.name=<model>` 

### ISSUE THREAD

**Issue by tnjordan** [iterative/mlem#342]
Using mlem to make docker container for my model to deploy in gcp cloud run.

It looks like mlem detects my python version as 3.10. But the base image `python:3.10.4-slim` fails to run ` apt-get install -y libgomp1`.

Minimally reproduce error with the following:
```Dockerfile
FROM python:3.10.4-slim
RUN apt-get install -y libgomp1
```

dvc doctor output:
```
DVC version: 2.11.0 (pip)
---------------------------------
Platform: Python 3.10.4 on Linux-5.15.0-1010-gcp-x86_64-with-glibc2.35
Supports:
        gs (gcsfs = 2022.2.0),
        webhdfs (fsspec = 2022.2.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda1
Caches: local
Remotes: gs
Workspace directory: ext4 on /dev/sda1
Repo: dvc (subdir), git
```
mlem version:
`🐶 MLEM Version: 0.2.2`

Logs:
```
(.venv) ubuntu@pfc-irm-dev-3:~/pfc-irm/ml$ mlem build S_model docker -c server.type=fastapi -c image.name=s_model
⏳️ Loading model from .mlem/model/S_model.mlem
💼 Adding model files...
🛠 Generating dockerfile...
💼 Adding sources...
💼 Generating requirements file...
🛠 Building docker image s_model:latest...
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: Step 1/10 : FROM python:3.10.4-slim
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: 
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: ---> 56cb06bdaede
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: Step 2/10 : WORKDIR /app
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: 
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: ---> Using cache
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: ---> 417be0be208c
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: Step 3/10 : RUN apt-get install -y libgomp1
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: 
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: ---> Running in eed58a844ad5
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: Reading package lists...
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: 
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: Building dependency tree...
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: Reading state information...
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: 
2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: E: Unable to locate package libgomp1

2022-07-12 22:58:10,633 [ERROR] mlem.contrib.docker.utils: {'errorDetail': {'code': 100, 'message': "The command '/bin/sh -c apt-get install -y libgomp1' returned a non-zero code: 100"}, 'error': "The command '/bin/sh -c apt-get install -y libgomp1' returned a non-zero code: 100"}
❌ Error calling docker: The command '/bin/sh -c apt-get install -y libgomp1' returned a non-zero code: 100
```

**Comment by tnjordan** [comment]
I was able to work around this issue by deleting 
```
- package_name: libgomp1
  type: unix
```
from the requirements section  of <model>.mlem file.

**Comment by mike0sv** [comment]
Do you use xgboost/catboost/lightgbm? Is you model working without libgomp1?

**Comment by tnjordan** [comment]
> Do you use xgboost/catboost/lightgbm? Is you model working without libgomp1?

I am using lightghm. It doesn't appear the container is working.

**Comment by aguschin** [comment]
This workaround uses MLEM's builder declaration. You could read about them in GS, [for example here](https://mlem.ai/doc/get-started/building).

First, declare a builder
```shell
$ mlem declare builder docker -c server.type=fastapi -c image.name=s_model docker-builder
```
This creates declaration for the builder:
```yaml
$ cat docker-builder.mlem
image:
  name: s_model
object_type: builder
server:
  type: fastapi
type: docker
```
Then, add the lines Mike posted. You should get this:
```yaml
$ cat docker-builder.mlem
args:
  templates_dir:
    - .  # or where you put pre install template file
image:
  name: s_model
object_type: builder
server:
  type: fastapi
type: docker
```
Finally, create empty `pre_install.j2` in your MLEM root dir (nearby the `docker-builder.mlem`)

@mike0sv, is this correct? Please edit this message if not.

**Comment by mike0sv** [comment]
Yes. You need to declare it first and edit because cli doesnt support setting list values yet

**Comment by aguschin** [comment]
@tnjordan, this is due to `typer`'s new release breaking our code. I've pinned the typer version in MLEM's `setup.py`. Could you please install the latest MLEM version? I've made a release few hours ago. This will fix the last error you posted.

**Comment by mike0sv** [comment]
Yeah, our release workflow failed and those versions are not on pip yet. As temporary workaround, set `MLEM_SOURCE=local` env

**Comment by tnjordan** [comment]
I was able to get it running by modifing my `pre_install.j2` file to be
```
RUN apt-get update
RUN apt-get install git -y
RUN pip install git+https://github.com/iterative/mlem.git@main
```

**Comment by aguschin** [comment]
Strange. It looks like PyPi took longer to update this time 🤔

**Comment by aguschin** [comment]
@mike0sv, I assume this is fixed?

**Comment by aguschin** [comment]
or we need https://github.com/iterative/mlem/issues/345 to close this one?

**Comment by mike0sv** [comment]
#345 is being done in #391 
it will still fail if you manually added `git+` requirement and did not add `git` package requirement, but I guess users will have to add it themselves for now
